# Simple workflow for deploying static content to GitHub Pages
name: Feature close

on:
  pull_request:
    types: [closed]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "feature-close"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: ${{ github.ref }}
      url: https://www.google.ch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
